/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_logging: () => void;
export const __wbg_gameoflifewasm_free: (a: number, b: number) => void;
export const gameoflifewasm_new: (a: number, b: number) => number;
export const gameoflifewasm_get_state: (a: number) => [number, number];
export const gameoflifewasm_step: (a: number) => void;
export const gameoflifewasm_set_cell: (a: number, b: number, c: number, d: number) => void;
export const gameoflifewasm_get_cell: (a: number, b: number, c: number) => number;
export const gameoflifewasm_toggle_cell: (a: number, b: number, c: number) => void;
export const gameoflifewasm_clear: (a: number) => void;
export const gameoflifewasm_resize: (a: number, b: number, c: number) => void;
export const gameoflifewasm_load_from_array: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const gameoflifewasm_get_dimensions: (a: number) => any;
export const gameoflifewasm_count_live_cells: (a: number) => number;
export const __wbg_gifrecorder_free: (a: number, b: number) => void;
export const gifrecorder_new: () => number;
export const gifrecorder_start_recording: (a: number, b: number, c: number, d: number) => [number, number];
export const gifrecorder_capture_frame: (a: number, b: number, c: number) => [number, number];
export const gifrecorder_stop_recording: (a: number) => [number, number, number, number];
export const gifrecorder_is_recording: (a: number) => number;
export const gifrecorder_get_frame_delay: (a: number) => number;
export const tick: (a: number, b: number) => [number, number];
export const sample_grid: () => [number, number];
export const index: (a: number, b: number) => number;
export const count_neighbors: (a: number, b: number, c: number, d: number) => number;
export const text_to_grid_with_buffer: (a: number, b: number, c: number) => [number, number, number];
export const parse_text_file: (a: number, b: number) => [number, number, number];
export const create_game: () => number;
export const create_game_with_size: (a: number, b: number) => number;
export const validate_dimensions: (a: number, b: number) => number;
export const get_version: () => [number, number];
export const main: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_3: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
