pub mod middleware;

use axum::{
    Router,
    body::Body,
    http::{Request, Response, StatusCode, header::CONTENT_TYPE},
    middleware::from_fn,
    routing::{get, get_service},
};

use std::convert::Infallible;
use std::fs;
use std::path::PathBuf;
use tower::service_fn;
use tower_http::{compression::CompressionLayer, services::ServeDir};

const FALLBACK_NOT_FOUND_PAGE: &[u8] = br#"<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Page not found</title></head>
<body><main><h1>Page not found</h1><p>The requested page does not exist.</p></main></body>
</html>
"#;

/// Builds the application router.
/// - `static_dir`: the directory for static assets generated by Astro.
/// - `wasm_dir`: the directory containing the WebAssembly bundle.
pub fn app(static_dir: &str, wasm_dir: &str) -> Router {
    let index_path = PathBuf::from(static_dir).join("index.html");
    let not_found_path = PathBuf::from(static_dir).join("404.html");
    let not_found_body =
        fs::read(not_found_path).unwrap_or_else(|_| FALLBACK_NOT_FOUND_PAGE.to_vec());
    let not_found_service = service_fn(move |_request: Request<Body>| {
        let body = not_found_body.clone();
        async move {
            Ok::<_, Infallible>(
                Response::builder()
                    .header(CONTENT_TYPE, "text/html; charset=utf-8")
                    .body(Body::from(body))
                    .expect("the static 404 response is valid"),
            )
        }
    });

    let static_service = get_service(
        ServeDir::new(static_dir)
            .precompressed_br()
            .precompressed_gzip()
            .not_found_service(not_found_service),
    );

    Router::new()
        .route("/healthz", get(|| async { (StatusCode::OK, "ok") }))
        .route(
            "/readyz",
            get(move || {
                let index_path = index_path.clone();
                async move {
                    match tokio::fs::metadata(index_path).await {
                        Ok(metadata) if metadata.is_file() => (StatusCode::OK, "ready"),
                        _ => (StatusCode::SERVICE_UNAVAILABLE, "static site unavailable"),
                    }
                }
            }),
        )
        .nest_service("/wasm", get_service(ServeDir::new(wasm_dir)))
        .fallback_service(static_service)
        .layer(CompressionLayer::new())
        .layer(from_fn(middleware::set_response_headers))
        .layer(from_fn(middleware::log_requests))
}
