pub mod game_of_life;
pub mod logging;
pub mod middleware;
pub mod routes;

use axum::{
    Router,
    middleware::from_fn,
    routing::{get, get_service, post},
};

use axum::http::{HeaderValue, header::CACHE_CONTROL};
use std::path::PathBuf;
use tower_http::{
    compression::CompressionLayer,
    services::{ServeDir, ServeFile},
    set_header::SetResponseHeaderLayer,
};

/// Builds the application router.
/// - `static_dir`: the directory for static assets generated by Astro.
/// - `wasm_dir`: the directory containing the WebAssembly bundle.
/// - `game_api`: the router for your Game of Life API endpoints.
pub fn app(static_dir: &str, wasm_dir: &str, game_api: Router) -> Router {
    let index_fallback = PathBuf::from(static_dir).join("index.html");

    let cache_layer = SetResponseHeaderLayer::if_not_present(
        CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=31536000, immutable"),
    );

    let static_service = get_service(
        ServeDir::new(static_dir)
            .precompressed_br()
            .precompressed_gzip()
            .not_found_service(ServeFile::new(index_fallback)),
    )
    .layer(cache_layer.clone());

    Router::new()
        .route("/sitemap.xml", get(routes::sitemap))
        .route("/api/logs", post(logging::ingest_frontend_log))
        .nest("/api/game-of-life", game_api)
        .nest_service(
            "/wasm",
            get_service(ServeDir::new(wasm_dir)).layer(cache_layer),
        )
        .fallback_service(static_service)
        .layer(CompressionLayer::new())
        .layer(from_fn(middleware::log_requests))
}
