[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+simd128",
  "-C", "target-feature=+bulk-memory", 
  "-C", "target-feature=+mutable-globals"
]

[unstable]
build-std = ["std", "panic_abort"]